export const INITIAL_STATE = {
  mode: "manual-simulation",
  deviceOnline: false,
  temperature: 25,
  humidity: 60,
  pressure: 101.3,
  heatIndex: 26,
  dewPoint: 18,
  absHumidity: 14,
  luminosity: 10000,
  rainLevel: 0,
  windSpeed: 0.0,
  windDirection: "N",
  brightness: 1,
  speed: 1,
  weather: "sunny",
  position: 0,
  openKey: null,
  chartData: [{ time: "0:00", temp: 25, hum: 60, pres: 101.3 }],
};
